chatroom/chat/urls.py
from django.urls import path, re_path

from . import views

app_name = "chat"
urlpatterns = [
    path("chat/", views.chatpage, name="chat-page"),
    path("chat/<str:room_name>/", views.room, name="room"),
    path("roomselect/<int:id>/", views.roomselect, name="roomselect"),
    path('chat/get_users/<term>', views.get_users, name='get_users'),
    re_path(r'^$', views.userlogin,name="login"),
    re_path(r'^logout/$', views.userlogout,name="logout"),
    re_path(r'^signup/$', views.usersignup,name="signup"),
]

chatroom/chatroom/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("chat.urls")),
    path("admin/", admin.site.urls),
]

chatroom/chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length=16, blank=True, null=True)

	def __str__(self):
		return self.user.username

class ChatRoom(models.Model):
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

class Chat(models.Model):
	content = models.CharField(max_length=1000)
	timestamp = models.DateTimeField(auto_now=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
	active = models.BooleanField(default=True)
	
	def __str__(self):
		return self.content

chatroom/chat/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import UserCreationForm
# from django.core.validators import MaxValueValidator

class NewUserForm(UserCreationForm):
    phone = forms.IntegerField()
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = User
        fields = ('first_name','last_name','email','phone','username','password1', 'password2')
        labels = {'phone': 'Phone Number',}    

chatroom/chat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from django.contrib import messages
import json

from django.contrib.sessions.models import Session
from django.utils import timezone

def get_all_logged_in_users():
	sessions = Session.objects.filter(expire_date__gte=timezone.now())
	uid_list = []

	for session in sessions:
		data = session.get_decoded()
		uid_list.append(data.get('_auth_user_id', None))

	return User.objects.filter(id__in=uid_list)


# Create your views here.
def userlogin(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return redirect('chat:chat-page')
			else:
				return HttpResponse('Account Not active')
		else:
			print('Some ome tried to login and faild')
			print('Username: {} password {}'.format(username,password))
			messages.error(request,f"User crediantials are wrong. Please login with proper user crediantials.")
			return HttpResponseRedirect(reverse('chat:login'))
            
	else:
		if request.user.is_authenticated:
			return redirect('chat:chat-page')
		return render(request, 'chat/login.html',{})

def userlogout(request):
	logout(request)
	return HttpResponseRedirect(reverse('chat:login'))


def usersignup(request):

	if request.method == 'POST':
		form = NewUserForm(request.POST)
		if form.is_valid():
			uname = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			user_present	=	User.objects.filter(username=uname.lower()).exists()
			email_present	=	User.objects.filter(email=email.lower()).exists()
			if user_present:
				messages.error(request,f"Entered username is already exist.Please login with the existing crediantial or use different username. ")
				return render(request, 'chat/signup.html',)
			elif email_present:
				messages.error(request,f"Entered email id is already exist.Please uses different EMail id. ")
				return render(request, 'chat/signup.html',)
			else:
				user = form.save()
				user.refresh_from_db()
				phone_number =  form.cleaned_data.get('phone')
				UserProfile.objects.update_or_create(user=user, defaults={'phone_number': phone_number},)
				user.save()
				messages.info(request,f"You have successfully registered,""You can login the portal using your login credentials")
				return redirect('chat:login')
		else:
			messages.error(request,form.errors)
			return redirect('chat:signup')
	else:
		form = NewUserForm()
		return render(request, 'chat/signup.html',{'form':form})

@login_required(login_url="chat:login")
def chatpage(request):
	if not request.user.is_authenticated:
		return redirect("chat:login")
	chatroom = ChatRoom.objects.all()
	chat = Chat.objects.filter(user=request.user).update(active=False)

	users = User.objects.exclude(username=request.user.username)
	return render(request, "chat/index.html",{'chatroom':chatroom, 'user':users})



@login_required(login_url="chat:login")
def room(request, room_name):
	room = ChatRoom.objects.filter(name=room_name).first()
	chats = []
	div = room_name.split('-')
	if int(div[0]) == request.user.id:
		user_obj = User.objects.get(id=int(div[1]))
	else:
		user_obj = User.objects.get(id=int(div[0]))

	if room:
		chats = Chat.objects.filter(room=room)
	else:
		room = ChatRoom(name=room_name)
		room.save()
	
	# user = get_all_logged_in_users()
	user = User.objects.exclude(username=request.user.username)

	return render(request, 'chat/room.html', {'user': user_obj, 'room_name': room_name, 'chats': chats,'active_users':user})

@login_required(login_url="chat:login")
def roomselect(request, id):
	i = request.user.id
	j = id
	add=""
	if i < j:
		add = str(i)+'-'+str(j)
	elif i>j :
		add = str(j)+'-'+str(i)
	
	chats = ChatRoom.objects.filter(name=add)
	if not chats:
		room = ChatRoom(name=add)
		room.save()
	return redirect('chat:room', room_name=add)

# This is for Autocomplete search for users
@login_required(login_url="chat:login")
def get_users(request,term):
	if request.method == 'GET':
		users = User.objects.filter(username__icontains = term )[:20]
		print(users)
		results = []
		for i in users:
			user_json = {}
			user_json['id'] = i.id
			user_json['label'] = i.username
			user_json['value'] = i.username
			results.append(user_json)
		data = json.dumps(results)
	else:
		data = 'fail'
	mimetype = 'application/json'
	return HttpResponse(data, mimetype)	

chatroom/chat/templates/chat/index.html
{% extends "base.html" %}
{% block title %}Chat Select{% endblock %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'index.css' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Chat Room</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chat:logout' %}">Sign Out</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="back-container">
        <div class="container-fluid front-container">
            <div class="back-top"></div>
            <div class="back-main"></div>
        </div>
        <div class="container front-container1">
            <div class="row chat-top">
                <div class="col-sm-4 border-right border-secondary">
                    <img src="{% static 'dp.png' %}" alt="" class="profile-image rounded-circle">
                    <span class="ml-2">{{request.user.get_full_name | capfirst}}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 contacts">
                    <div class="contact-table-scroll">
                        <table class="table table-hover">
                            <tbody>
                                <br>
                                <tr>                                    
                                    <form method="post" id="serach_form">
                                        {% csrf_token %}
                                        <input type="search" placeholder="Search..."  id="user_search" onkeyup="loadusers(this.id)" required autofocus>
                                        <button type="submit" id="search">Search</button>
                                        <input type='hidden' class="form-control" id='user_val' name='user_val'>
                                    </form>
                                </tr>
                                <br>
                                {% for i in user %}
                                <tr>
                                    <td><img src="{% static 'dp.png' %}" alt="" class="profile-image rounded-circle">
                                    </td>
                                    <td><a href="{% url 'chat:roomselect' id=i.id %}" style="color:black; text-decoration: none;">{{i.get_full_name | capfirst}}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script>
        // document.querySelector('#room-name-input').focus();
        // document.querySelector('#room-name-input').onkeyup = function(e) {
        //     if (e.keyCode === 13) {  // enter, return
        //         document.querySelector('#room-name-submit').click();
        //     }
        // };

        // document.querySelector('#room-name-submit').onclick = function(e) {
        //     var roomName = document.querySelector('#room-name-input').value;
        //     window.location.pathname = '/chat/' + roomName + '/';
        // };

    </script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script>
    function loadusers(mat_id)
	{
		var mat_id2='#'+mat_id;				
		var mat_type='';
		var getData = function (request, response) {
			$.getJSON(
				'get_users/' + request.term,
				function (data) {
					// console.log(data);
					response(data);
				});
		};
	 
		var selectItem = function (event, ui) {
			// console.log(ui);
			$(mat_id2).val(ui.item.label);				
			$('#user_val').val(ui.item.id);				
            
            action_src = "{% url 'chat:roomselect' id=0 %}".replace('0', $('#user_val').val());
            console.log(action_src)
            var your_form = document.getElementById('serach_form');
            your_form.action = action_src ;
			return false;
		}
	 
		$(mat_id2).autocomplete({
			source: getData,
			select: selectItem,
			minLength: 1,
			maxShowItems:5,
			scroll:true,
            				
		});
	}
</script>
{% endblock %}

chatroom/chat/templates/chat/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block body_block %}
{% if messages %}
      {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
<style type="text/css">
        body{background: #000}.card{border: none;height: 320px}.forms-inputs{position: relative}.forms-inputs span{position: absolute;top:-18px;left: 10px;background-color: #fff;padding: 5px 10px;font-size: 15px}.forms-inputs input{height: 50px;border: 2px solid #eee}.forms-inputs input:focus{box-shadow: none;outline: none;border: 2px solid #000}.btn{height: 50px}.success-data{display: flex;flex-direction: column}.bxs-badge-check{font-size: 90px}
    </style>
    <body>     
        <form method="POST">
            {% csrf_token %}
            <div class="container mt-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5" id="form1">
                            <div class="form-data" v-if="!submitted">
                                <div class="forms-inputs mb-4"> 
                                    <span>Username</span> 
                                    <input name="username" autocomplete="off" type="text" class="form-control">
                                </div>
                                <div class="forms-inputs mb-4"> <span>Password</span> 
                                    <input name="password" autocomplete="off" type="password" class="form-control">
                                </div>
                                <div class="mb-3"> <button v-on:click.stop.prevent="submit" class="btn btn-dark w-100">Login</button> </div>
                                <div class="mb-3"> <a href="{% url 'chat:signup' %}" v-on:click.stop.prevent="submit" class="btn btn-primary w-100">Sign up</a> </div>
                            </div>
                            <!-- <div class="success-data" v-else>
                                <div class="text-center d-flex flex-column"> <i class='bx bxs-badge-check'></i> <span class="text-center fs-1">You have been logged in <br> Successfully</span> </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </body>
{% endblock %}

chatroom/chat/templates/chat/room.html
{% extends "base.html" %}
{% block title %}Chat with user{% endblock %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'index.css' %}">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Chat Room</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link my-2 my-sm-0" href="{% url 'chat:logout' %}">Sign Out</a>
            </li>
        </ul>
    </div>
</nav>
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row chat-top">
            <div class="col-sm-4 border-right border-secondary">
                <img src="{% static 'dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{request.user.get_full_name | capfirst}}</span>

            </div>
            <div class="col-sm-8">
                
                <img src="{% static 'dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{user.get_full_name | capfirst}}</span>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            <br>
                                <tr>                                    
                                    <form method="post" id="serach_form">
                                        {% csrf_token %}
                                        <input type="search" placeholder="Search..."  id="user_search" onkeyup="loadusers(this.id)" required autofocus>
                                        <button type="submit" id="search">Search</button>
                                        <input type='hidden' class="form-control" id='user_val' name='user_val'>
                                    </form>
                                </tr>
                                <br>
                            {% for user in active_users %}
                            <tr>
                                <td><img src="{% static 'dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url 'chat:roomselect' id=user.id %}" style="text-decoration: none; color: black;">{{user.get_full_name | capfirst}} </a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>

            <div class="col-sm-8 message-area">
                <div class="message-table-scroll">
                    <table class="table">
                        <tbody id='chat-log'>
                            {% for chat in chats.all %}
                            {% if chat.user.id == request.user.id %}
                            <tr>
                                <td>
                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded message sender">
                                        {{ chat.content }}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{chat.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>
                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded message receiver">
                                        {{ chat.content }}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{chat.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row message-box p-3">
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="chat-message-input" placeholder="Write message...">

                    </div>
                    <div class="col-sm-2 mt-1">
                        <div class="control">
                            <button class="btn btn-success" id="chat-message-submit">Submit</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>
{{ room_name|json_script:"room-name" }}
{{user.id|json_script:"json-username"}}
{{ request.user.id|json_script:"user_id" }}
{{request.user.username|json_script:"json-message-username"}}



    <script>

        $(document).ready(function(){
            $('#chat-log').animate({ scrollTop: $(document).height() }, 1200);

            $('#chat-log').bind('DOMSubtreeModified', function(){
              console.log('changed');
              $('#chat-log').animate({ scrollTop: $(document).height() }, 1200);
            });
        });

        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const chatLog = document.querySelector('#chat-log')
        
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const messageElement = document.createElement('div')
            const userId = data['user_id']
            messageElement.innerText = data.message
            const loggedInUserId = JSON.parse(document.getElementById('user_id').textContent)
            // document.querySelector('#chat-log').value += (data.message + '\n');
            // messageElement.innerText += '\n '
            if (userId === loggedInUserId) {
                messageElement.classList.add('message', 'sender')

            } else {
                messageElement.classList.add('message', 'receiver')
            }

            chatLog.appendChild(messageElement)

            if( chatLog != " ")
            {
                playSound();
            }

            if (document.querySelector('#emptyText')) {
                document.querySelector('#emptyText').remove()
            }
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            // message += ' \n Text from {{ request.user.username }}';
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
        function playSound() {
            var audio = new Audio('{% static "audio_file.mp3" %}');
            audio.play();
        }

    </script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
    <script>
        function loadusers(mat_id)
        {
            var mat_id2='#'+mat_id;				
            var mat_type='';
            var getData = function (request, response) {
                $.getJSON(
                    'get_users/' + request.term,
                    function (data) {
                        // console.log(data);
                        response(data);
                    });
            };
         
            var selectItem = function (event, ui) {
                // console.log(ui);
                $(mat_id2).val(ui.item.label);				
                $('#user_val').val(ui.item.id);				
                
                action_src = "{% url 'chat:roomselect' id=0 %}".replace('0', $('#user_val').val());
                console.log(action_src)
                var your_form = document.getElementById('serach_form');
                your_form.action = action_src ;
                return false;
            }
         
            $(mat_id2).autocomplete({
                source: getData,
                select: selectItem,
                minLength: 1,
                maxShowItems:5,
                scroll:true,
                                
            });
        }
    </script>
{% endblock %}

chatroom/chat/templates/chat/signup.html
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}
{% block body_block %}
	{% if messages %}
      {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <!-- <style type="text/css">
        body{background: #000}.card{border: none;height: 320px}.forms-inputs{position: relative}.forms-inputs span{position: absolute;top:-18px;left: 10px;background-color: #fff;padding: 5px 10px;font-size: 15px}.forms-inputs input{height: 50px;border: 2px solid #eee}.forms-inputs input:focus{box-shadow: none;outline: none;border: 2px solid #000}.btn{height: 50px}.success-data{display: flex;flex-direction: column}.bxs-badge-check{font-size: 90px}
    </style>
    <body> 

	<div class="container" style="padding-top:15px;">
		<div class="container-fluid">
			<div class="col-md-12" style="justify-content: center;display: flex;margin: 40px 50px;border: 3px solid white;padding: 30px;background-color: gray;">
				<form method="post" style="padding: 15px;" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="row" >
						<div class="col-md-12" id="user_signup">
							{{ form.as_p }}
						</div>
					</div>
					<br>
					<input  type="submit" value="Sign up" class="btn btn-primary">
				</form>
			</div>
		</div>
	</div>
</body> -->


	<style>
		body {font-family: Arial, Helvetica, sans-serif;}
		* {box-sizing: border-box}		
		hr {
			border: 1px solid #f1f1f1;
			margin-bottom: 25px;
		}
		
		/* Set a style for all buttons */
		.signupbtn, .cancelbtn {
			background-color: #04AA6D;
			color: white;
			padding: 14px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 100%;
			opacity: 0.9;
		}
		
		button:hover {
			opacity:1;
		}
		
		/* Extra styles for the cancel button */
		.cancelbtn {
			padding: 14px 20px;
			background-color: #f44336;
		}
		
		/* Float cancel and signup buttons and add an equal width */
		.cancelbtn, .signupbtn {
			float: left;
			width: 50%;
		}
		
		.clearfix::after {
			content: "";
			clear: both;
			display: table;
		}
		
		/* Change styles for cancel button and signup button on extra small screens */
		@media screen and (max-width: 300px) {
			.cancelbtn, .signupbtn {
				width: 100%;
			}
		}
	</style>
	<body>
		<div class="row align-items-center" style="height: 100vh;" >
			<form method="post" enctype="multipart/form-data">
				<div class="container-fluid" >
					<div class="mx-auto col-10 col-md-8 col-lg-6" style=" border: 1px solid black; padding: 50px; justify-content: center;display: block;margin: 40px 50px;">
						
						<h1>Sign Up</h1>
						<p>Please fill in this form to create an account.</p>
						<hr>
						{% csrf_token %}
						{{ form.as_p }}
						<div class="clearfix">
							<a href="{% url 'chat:login' %}" style="text-decoration: none;" type="button" class="btn cancelbtn">Cancel</a>
							<button type="submit" id="signup" class="signupbtn">Sign Up</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</body>



{% endblock %}

chatroom/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        {% load static %}
        <!-- <link rel="stylesheet" href="{% static '/bootstrap/dist/css/bootstrap.min.css' %}"> -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    </head>
    <!-- <body> -->

        {% block body_block %}

	    {% endblock %}
    <!-- <body> -->
</html>